### PR TITLE
added: UAV with CAS capabilities now available at MHQ under create vehicle menu

### PR DESCRIPTION
**Pull request by longtimegamer**
players can spawn a Greyhawk, 6 laser guided AT missiles

I don't know how many points to deduct for ranked servers but please change to whatever makes sense.

### CODE REVIEW

**Comment by Xeno69** [comment]
Please add a param which can enable it, default disabled

**Comment by longtimegamer** [comment]
now requires d_enable_extra_cas == 1

**Comment by longtimegamer** [comment]
hmm that expression does not work in the preinit, need to think about it

**Comment by longtimegamer** [comment]
I don't understand some of the filenames and function names in Domination.

fn_p_o_ar.sqf and functions contained are driven by "a" "a2" "a2r" etc.  Other developers (like me) have no idea what that means and there are no comments anywhere.

This happens everywhere in Domination.  Please consider this for Arma 4.

**Comment by longtimegamer** [comment]
This is better with an MHQ function like you described.  I already added some stuff in another branch.

**Pull request closed without merging**
