### PR TITLE
airdrop fighting vehicles and some bug fixes

### PR DESCRIPTION
**Pull request by longtimegamer**
I added some vehicles to the airdrop if d_with_airdrop == 2

image

### CODE REVIEW

**Comment by longtimegamer** [comment]
I am still testing this.  Playing SOG maps gives the players a message airdrop not available.  Probably related to this pull request.

**Comment by longtimegamer** [comment]
Ok, I fixed the problem.  This is ready to merge.

**Comment by longtimegamer** [comment]
I also added two factions using the existing definitions for CUP Russian Armed Forces and CUP Takistani Armed Forces.

**Comment by longtimegamer** [comment]
I also added OPFOR CUP Russian Armed Forces Winter and INDFOR ION PMC and ION PMC Arctic.

**Comment by longtimegamer** [comment]
ok I think that is all, this pull request is getting long

**Comment by Xeno69** [comment]
I'm sorry but I won't merge this. 

1. You replace simple boolean checks which cost virtually no CPU cycles with case sensivtive string checks that are quite CPU heavy (laser).
2. ptakeweapon does checks even if ranked is disabled (if weapons are missing then parts of the classes have to be added like it is done for other mods)
3. d_cas_plane_ai can also be an array so the check has to stay

There are probably some more issues.

**Comment by longtimegamer** [comment]
1. Sure, easy fix
2. You should look again. This bug has broken Domination for years.
3. Sure, easy fix.

"probably more issues" - This is not helpful.

**Comment by Xeno69** [comment]
I know that it isn't helpfull but as I have no A3 on my drives anymore I can only check here on GitHub.

But for example, why do you pv these variables?

	publicVariable "d_sm_ammotrucktype_own_side";
	publicVariable "d_sm_apc_own_side";
	publicVariable "d_sm_HunterGMG_own_side";
	publicVariable "d_sm_tank_own_side";

**Comment by longtimegamer** [comment]
I can't work with "probably more issues." I will leave you alone.

**Comment by Xeno69** [comment]
I'm merging this now, please fix the issues I've mentioned.

**Comment by Xeno69** [comment]
And you don't need to pv those, only when d_with_airdrop == 2

**Pull request merged**
