### PR TITLE
added: new guided CAS ordnance: 500 lb bomb

### PR DESCRIPTION
**Pull request by longtimegamer**
I have always wanted to kill a tank with my laser designator.  :)  This is a bit larger than the CAS airstrike and it can kill armor.  I hope this doesn't negatively affect game balance.  Please fix anything you think is appropriate (such as points on ranked server).

I'm not sure if the scoring works correctly.  ie-- credits for enemy kills, penalties for civs, cost in points on ranked server

I may add ambientFlyby later, probably not since this should be high altitude.  The bomb actually only falls 500m but it looks good.

### CODE REVIEW

**Comment by Xeno69** [comment]
I won't add it now as 4.59 is already done and packed. So after 4.59 it will make it into master

**Comment by longtimegamer** [comment]
That's good. The score system does not work with the new bomb so this gives me time to think about a fix.

**Comment by longtimegamer** [comment]
fixed by setting instigator on the bomb

**Comment by Xeno69** [comment]
Ok, I'm going to add it before 4.59 :)

**Pull request merged**
