### PR TITLE
Angry bots

### PR DESCRIPTION
**Pull request by longtimegamer**
These settings allow the admin to choose special bot behaviors applied when fn_makemgroup is invoked.  Default gameplay is not affected by the special bot changes unless the admin explicitly chooses the new behaviors.

In this pull request there are four new AI settings for allmen and snipers bot behavior:

* all enemy infantry bots: on an interval, reveal nearby players with "reveal 4" within configurable radius

* all enemy infantry bots: on an interval, check line-of-sight with players and doSuppressiveFire if LOS or isVisible are true within configurable radius

* all enemy infantry bots: on an interval, if _fired is true then frequently do "setAmmo 1" (this helps to balance new shooting behavior vs running out of ammo too quickly)

* all enemy infantry bots which are free to move: on an interval, if bot is a leader then order the group to move to location of nearest player within configurable radius

The new optional behaviors have a significant impact on performance as the frequent use of "reveal" and "doSuppressiveFire" and line-of-sight calculation requires heavy CPU.  However, with reasonably strong server hardware the results are fantastic bot fights with very unique movement.

I renamed the sniper script and included both sniper and non-sniper behavior in the same file.  The sniper behavior is applied if the unit is in a group with prefix "Sniper" assigned by setGroupId.  I also reorganized the mission parameters section related to AI behaviors and removed sniper shake skill (aimingShake isn't very useful and aimingAccuracy is already parameterized).

This has been tested on MP server for a while and has been certified as "super fun."  However please feel free to decline the pull request if you feel it will reduce mission performance or even better, help fix my bad code... :)

### CODE REVIEW

**Comment by longtimegamer** [comment]
By the way, you can see this behavior in-game on the "Camp Flabanabba" server.  Very challenging fight.  :)

**Comment by Xeno69** [comment]
I'll look into it next week. Currently I just wait and see if anybody reports a problem after 4.24. But it looks quite good atm and it looks like no hotfix is needed.

**Comment by longtimegamer** [comment]
Ok, thanks.  No hurry.

**Comment by Xeno69** [comment]
I have added it, let's work from here

**Pull request merged**
