### PR TITLE
fixed: simpler logic in occupyhouse script

### PR DESCRIPTION
**Pull request by longtimegamer**
fixes in occupy script for civs
occupy script simpler forEach instead of for loop so script does not skip positions

### CODE REVIEW

**Comment by Xeno69** [comment]
Add
#define __DEBUG__ 
at the beginning of the script.

**Comment by longtimegamer** [comment]
does that enable all trace?  is it possible to enable trace 1, trace 2 etc?

**Comment by Xeno69** [comment]
There are no levels

Trace 1 2 3 just means 1 2 or 3 variables you can add to a trace

**Comment by Xeno69** [comment]
It's just simple macros which are completely removed when __DEBUG__ is not defined

**Comment by Xeno69** [comment]
Btw, I only commit to A3_DEV now as I already use the A3 2.10 DEV version and I am adding missionProfileNamespace already.

**Comment by Xeno69** [comment]
A3_DEV Domination branch that is

**Pull request merged**
