### PR TITLE
added: parameter to hide/show FPS and status bars to allow a no-HUD playing experience

### PR DESCRIPTION
**Pull request by longtimegamer**
Parameters to play with a clean screen and no HUD (hide FPS and/or status-arty toolbars).

### CODE REVIEW

**Comment by Xeno69** [comment]
That's not something for a parameter, the player himself should be the one who decides it. So more a setting for status dialog. Rejected :)

**Comment by longtimegamer** [comment]
Ouch, the pain.  :)

That is a better solution.  I haven't modified the status dialog before.  This should be exciting...

**Comment by longtimegamer** [comment]
Here's a teaser... 

image

**Comment by longtimegamer** [comment]
Here's a teaser...

image

**Comment by Xeno69** [comment]
You are checking the key to disable the UI? Isn't it the backspace key?

**Comment by longtimegamer** [comment]
Backspace key doesn't seem to have any effect.  There is a key to disable the UI?

Just to clarify, I am referring to the artillery and domination scoreboard toolbars (see image):

image

The other status bars are Arma menus and can be hidden with a custom difficulty level but I can't find a key to hide the Domination menus.

**Comment by Xeno69** [comment]
I think it was stream friendly UI but might not be a key but a video options setting.

**Comment by Xeno69** [comment]
https://community.bistudio.com/wiki/isStreamFriendlyUIEnabled

**Comment by longtimegamer** [comment]
Ok, thanks.  I think this is all client side and can be determined by client's isStreamFriendlyUIEnabled.  I will try later.

**Comment by longtimegamer** [comment]
Resubmitting with the UI logic linked to isStreamFriendlyUIEnabled.

**Comment by longtimegamer** [comment]
Still junk commits, cleaning up and opening a new PR.

**Pull request closed without merging**
