### PR TITLE
Maintarget event guerrilla tanks

### PR DESCRIPTION
**Pull request by longtimegamer**
Create a couple of guerrilla tanks in a nearby location and give them a search-and-destroy waypoint in the center of the current maintarget.

There is some vehicle creation scripting here that may be helpful spawning tanks using nearestroads.  By restricting creation positions to only roads it is much more reliable to find a position that won't cause the vehicle to explode.

### CODE REVIEW

**Comment by Xeno69** [comment]
I've added it already to master. And I made some code changes to all event missions

Concerning guerrilla tanks. The IFA3 version has guerrilla units on the player side (beside it won't look nice if some Leo 2 suddenly drives around a WW2 setting, same for the CUP versions).
Maybe you can look into that again. The only versions which use guerrilla units as enemies are the tvt versions.

**Comment by longtimegamer** [comment]
Thanks for the code improvements and thanks for the heads up for IFA3 and CUP.  I will select different tanks for those.

The guerrilla (independent) friend/enemy list is interesting.  My preference was for the guerrilla side to be hostile to both Opfor and Blufor.  The default is for Independent friendly to Blufor and enemy to Opfor.  I was considering making that a mission parameter.  Does this break Domination?

`#ifndef __TT__
west setFriend [resistance, 0];
resistance setFriend [west, 0];
#endif`

**Comment by Xeno69** [comment]
How about spawning the independent vehicle and crew and switch the crew side to the current enemy side?

Use d_fnc_spawnvehicle function for example.

[position, angle, classname, d_side_enemy] spawn d_fnc_spawnvehicle
(Returns [_veh, _crew, _grp] )

**Comment by longtimegamer** [comment]
Thanks, that can be useful.

I will not try to modify the side hostilities for this mission event.  If the players are Blufor then they will be happy to see the guerrillas.  If the players are Opfor then they better prepare for enemy armor.  :)

I will definitely try to fix the IFA3 tank so it is a better fit for the environment.

**Comment by longtimegamer** [comment]
Actually I will probably simplify this to spawn armor on the same or opposite side as the players.  I was hoping the Independent units could be hostile to both Opfor and Blufor but it looks like setFriend could cause problems.  I think using d_enemy_side and d_player_side will be better.

I will push an update for that soon.

**Comment by longtimegamer** [comment]
Hmm ok not soon.  I want to test some stuff before making more changes.

I think the guerrilla tanks work. ie-- in my opinion it can be released in 4.30 .  At least it hasn't crashed my server yet... :D

For now there is PR #148 to fix the tanks in IFA3.

**Pull request merged**
