### PR TITLE
added: increased range of possible sniper spawn positions to allow fo…

### PR DESCRIPTION
**Pull request by longtimegamer**
…r better shooting on the main target (425m radius)

added: sniper down posture sleeps for a random period of time to keep cover when no targets are found
added: snipers now change posture to obtain line of sight
added: snipers now have spotters (2 units in sniper group)
added: sniper parameters for skill (general and aimingShake) and awareness (default behavior or with sniper script awareness)
added: sniper groups can now engage at distances of more than 400m using script by HallyG and dlegion
added: SniperTeam added to Opfor and Blufor
added: sniper positions in buildings now sorted by highest elevation on Z axis (no longer sorted by building height)
added: sniper target check using checkVisibility using script by sarogahtyp
added: sniper now chooses nearest target using script by Jezuro

### CODE REVIEW

**Comment by longtimegamer** [comment]
These are some features that I implemented to make snipers more fun.  For this feature I collected several solutions from various forum posts.  I attempted to credit the original authors in the release notes.

**Comment by longtimegamer** [comment]
I noticed the current master is creating error logs so I wasn't able to see this latest merged code run cleanly.

I've been running this feature on my server for a while, feel free to checkout "Camp Flabanabba" to see it.

**Comment by longtimegamer** [comment]
Nooooooooooo CRLF again???  My nemesis...

**Comment by longtimegamer** [comment]
Here's a text based patch file to help read the changes.

[domination-sniper-patch.txt](https://github.com/Xeno69/Domination/files/3558141/domination-sniper-patch.txt)

**Comment by Xeno69** [comment]
I have disabled d_enemy_garrison_troop_sniper_awareness as default (0).
I've tried to optimize the hallyg_dlegion_Snipe script a little bit but it still is a performance hog.

**Comment by longtimegamer** [comment]
Understood.  The awareness uses both vector calculation and the standard BIS checkVisibility.  Maybe removing the vector calculation is better since it behaves correctly with just checkVisibility.

I also didn't want to affect the default gameplay so the sniper count is zero by default.  This sniper feature might be considered controversial.  The reveal command is basically cheating for the bot sniper...  Bot-awareness plus the default 50 caliber weapon can make snipers too powerful.  It needs to be tuned with the skill parameter, in my opinion.  I also want to move away from the 50 cal sniper weapon to prevent the bots from literally shooting through buildings.

**Comment by Xeno69** [comment]
Beside some kind of cheating reveal is also bad for performance.

**Pull request merged**
