### PR TITLE
disable voices

### PR DESCRIPTION
**Pull request by longtimegamer**
added: parameter to disable voices, currently only works for VN map using their module

Sets disable voices to true by default on cam_lao_nam.

### CODE REVIEW

**Comment by longtimegamer** [comment]
The talking and screaming ruin a great map...

**Comment by Xeno69** [comment]
I actually like the voices very much. And just for VN?

**Comment by longtimegamer** [comment]
> I actually like the voices very much.

Wow, I found someone who likes the VN voices!

**Comment by longtimegamer** [comment]
I changed the default so the VN voices are enabled.

> And just for VN?

I would like to turn off the talking on any map but I'm not sure about the best way to implement that feature.  The VN map creators gave us a module to disable the voices.  The module currently disables both Blufor and Opfor but next VN release will allow selective muting by class.  I don't know if other maps make that kind of module available?  Script solutions like `setSpeaker noVoice` and `disableConversations` didn't work for me, maybe something wrong with my code.

**Comment by Xeno69** [comment]
I think they have a script running in the background

**Comment by longtimegamer** [comment]
Hmmm perhaps it will work with `setSpeaker / disableConversations` on other maps and only VM uses the special module.  I will look.

**Pull request merged**
