### PR TITLE
optionally load and compile from a text file "domination.cfg" in Arma server root dir

### PR DESCRIPTION
**Pull request by longtimegamer**
This provides a way to load mission parameters for people (like me) who do not use an external database.  Requires -filePatching enabled on server.  The file contents are compiled.

example domination.cfg file:

d_enablefatigue=0;
d_enablesway=0;

Parameters will show default setting for fatigue and sway but when mission starts the value from the text file will be used.

### CODE REVIEW

**Comment by longtimegamer** [comment]
Also added the new high / very higher grass layer values to namespace.

**Comment by Xeno69** [comment]
There is now FileExists in A3 DEV...

**Comment by longtimegamer** [comment]
Yes but I'm avoiding that branch until my brain is ready for it... 😄

**Comment by Xeno69** [comment]
Well, lots of changes in the Domi A3 branch...

I've changed your addition already to FileExists.

And changed to call compile preprocessFileLineNumbers, because that way comments can be added preprocess stuff can be added.

**Comment by longtimegamer** [comment]
Thanks, much better.

**Comment by longtimegamer** [comment]
This PR isn't working with a dedicated server.  The global variables are probably not being set correctly and they have no effect.  Works with Eden however.

I will come back and look at this later.

**Pull request merged**
