### PR TITLE
Phronk's Furniture

### PR DESCRIPTION
**Pull request by longtimegamer**
This adds Phronk's Furniture to Domination.

New furniture server parameter is off by default.  Client parameter is initially set to equal the server parameter by default but may be toggled by the client.  If the server parameter is set to true then the client sees an option on the dashboard to enable/disable with a checkbox.

### CODE REVIEW

**Comment by longtimegamer** [comment]
Hmmm this works on localhost but not working on dedicated server.  I am still looking at it...

**Comment by longtimegamer** [comment]
Not ready yet.

**Comment by longtimegamer** [comment]
Some background:

Phronk's Furniture is very nice but it seems to hurt client-side performance for low or mid-range PCs.   I wanted to provide a client-side toggle so players can "opt-out."  Unfortunately the server FPS is also too low...  when furniture area triggers are activated/deactivated it causes server lag.  Depending on player location server may be required to run several areas and then the server lags more.  Very cool idea but even with reduced/disabled client-side settings it is still too hard on server FPS as it is currently coded.

**Comment by Xeno69** [comment]
The more objects you use, even simple ones, the more performance it costs.

Especially objects which the player may never see are pretty much unnecessary.

There's a reason why I do not make bases with a gazillion of objects, the player is 99% of the time playing not at base.

**Comment by longtimegamer** [comment]
I think the idea could work with a clever way to avoid synchronizing with the server, maybe push pre-generated compositions to the client.  Current implementation does not work however.

**Comment by Xeno69** [comment]
Is it really worth it? What do players in Domination do? Watching furniture or shooting? :)

I think for upcoming releases it is more important to give the players something more to do in form of new events, side mission, etc. It's probably better to use some FPS in that area than in furniture.

**Comment by longtimegamer** [comment]
Call me crazy but I would buy furniture DLC.  :)

**Comment by Xeno69** [comment]
Maybe in Arma Reforger :D

**Pull request closed without merging**
