### PR TITLE
removed unnecessary function (d_fnc_m_a_h_a) from a script

### PR DESCRIPTION
**Pull request by alexvladn**

### CODE REVIEW

**Comment by Xeno69** [comment]
I can't remove the function but have to find a way to make it work again.
It adds points to the person who spawned the mash when another player heals himself in the ranked version and when a database is available.

Already thinking about moving back to the "old" mash tent version...

**Comment by alexvladn** [comment]
as u wish, sir :)

**Comment by Xeno69** [comment]
Nope, wasn't obsolete.

Anyway, got it working with inGameUISetEventHandler , this ticket is now obsolete.

Btw... 

Added: You'll now also see friendly AI units names above their heads when with ai is enabled

**Comment by alexvladn** [comment]
Xeno, thx a lot! That was i need for a long time.
ps pls chek your paypal account.

**Pull request closed without merging**
