### PR TITLE
additional logic and parameters to control number of guard and camp groups spawned, other fixes

### PR DESCRIPTION
**Pull request by longtimegamer**
added: parameters for number of patrol and guard/camps spawned, d_priority_target implemented for most infantry
fixed: "marked for death" survival event

### CODE REVIEW

**Comment by longtimegamer** [comment]
some rural areas (SOG) are better with more enemy patrols

**Comment by longtimegamer** [comment]
The new parameters for footpatrol are throwing an error.

It looks like this only applies to games where the new mission parameter is being used.  I don't think this affects any players in the community but I will get it fixed.


`15:35:30 Error in expression <2 = (_this # 0) select (_this # 1);
if (_a_vng2 # 0 > 0) then {
if (d_always_max>
15:35:30   Error position: <_a_vng2 # 0 > 0) then {
if (d_always_max>
15:35:30   Error Undefined variable in expression: _a_vng2
15:35:30 File mpmissions\__cur_mp.altis\server\fn_createmaintarget.sqf..., line 11
15:35:30 Error in expression <2 = (_this # 0) select (_this # 1);
if (_a_vng2 # 0 > 0) then {
if (d_always_max>
15:35:30   Error position: <_a_vng2 # 0 > 0) then {
if (d_always_max>
15:35:30   Error Undefined variable in expression: _a_vng2
15:35:30 File mpmissions\__cur_mp.altis\server\fn_createmaintarget.sqf..., line 11
15:35:30 Error in expression <_this # 0) select (_this # 1)) # 0;
if (_a_vng2 # 0 > 0) then {
private _num_ret>
15:35:30   Error position: <_a_vng2 # 0 > 0) then {
private _num_ret>
15:35:30   Error Undefined variable in expression: _a_vng2
15:35:30 File mpmissions\__cur_mp.altis\server\fn_createmaintarget.sqf..., line 27
15:35:30 Error in expression <_this # 0) select (_this # 1)) # 0;
if (_a_vng2 # 0 > 0) then {
private _num_ret>
`

**Comment by Xeno69** [comment]
Ok

**Comment by Xeno69** [comment]
It's reverted.

**Comment by longtimegamer** [comment]
Thank you, sorry about that.  Did this cause #292  ?

**Comment by Xeno69** [comment]
I hope so :)

**Comment by longtimegamer** [comment]
Ok it looks like this did not cause #292 .  I will try this code again in a separate PR.

**Pull request merged**
