### PR TITLE
show headshot details in side chat

### PR DESCRIPTION
**Pull request by longtimegamer**
added: mission parameter to show player headshots and distance in side chat

d_show_headshots default 0 is current behavior with no headshot indicator
d_show_headshots 1 will show icon client side only (quickly fading skull and number of meters?  not yet implemented)
d_show_headshots 2 shows client and server via side chat

### CODE REVIEW

**Comment by longtimegamer** [comment]
I don't have any code to show the client side indicator yet but I would like it to show a skull and crosshairs and maybe a small font inset with the distance in meters (rounded) and then quickly disappear.

The server side indicator is "noisy" since it shows a message to all players but it is nice to recognize when your teammates are making long headshots.

**Comment by Xeno69** [comment]
Maybe reduce kbTell to the player group.

And don't forget the icon :)

**Comment by longtimegamer** [comment]
@Xeno69 I wanted to add a parameter value to notify the player's group but I can't figure out the kbTell.  I have been using d_kb_logic1 and the side topic but I'm not sure how to narrow this to only the group.  Do you have any examples or suggestions?

**Comment by Xeno69** [comment]
Instead of using
`d_kbtel_chan`
in
https://github.com/Xeno69/Domination/blob/6adedaee2f7bc22fe1b9a4cb3b4d85b61a5a00b4/co30_Domination.Altis/server/fn_addheadshot.sqf#L26
use
`"GROUP"`

**Comment by Xeno69** [comment]
Hm, thinking about it again... Group would be the logic group in that case, means players won't see the message...Maybe don't use  kbTell but the message system which displays the add score messages

**Pull request merged**
