### PR TITLE
added: new missiontype where side missions now spawn close to main target and must be cleared before main target is considered clear

### PR DESCRIPTION
**Pull request by longtimegamer**
This code selects sidemissions that are near the current maintarget with a new d_MissionType == 3. 
 This is a continuation of PR #115 but adds the sidemission as a victory requirement for maintarget.

### CODE REVIEW

**Comment by longtimegamer** [comment]
This PR is not ready for merge but I wanted to provide some visibility in the direction.  I am still making changes.

**Comment by longtimegamer** [comment]
One change I would like to make is to "whitelist" certain sidemissions that work well with a maintarget and only choose from that list when embedding a sidemission.  I am also considering only embedding one sidemission per target.  The current code requires the players to beat all sidemissions within X radius before maintarget is allowed to clear and perhaps just one sidemission is better.

**Comment by longtimegamer** [comment]
Ok this is ready for review.  It now chooses one sidemission within 2000m of maintarget marker and that sidemission must be cleared to meet the maintarget victory condition.  The default gameplay should not be affected by this change; this code only executes when the new mission parameter for d_MissionType is selected.

Please let me know what you think.  I realize this is another big change and I want to be sure the code is good quality.

I also wanted to commit this change now because you commented about creating new sidemission types.  I thought this would fit well with that idea.  Since the sidemission fights are near maintarget enemies there could be a type of sidemission designed to fit that scenario, such as protecting a moving VIP through an actual maintarget "warzone" or any of the existing sidemissions that fit well with a "warzone" setting.

**Comment by longtimegamer** [comment]
One other comment: creating an eligible sidemission at the same time as the maintarget reduces the chance of spawning within view of players.  Also there is only one sidemission selected with this new mode so the chance of spawning near players already engaged in maintarget is low.  I'm hoping this will avoid tanks magically appearing in our faces.

**Comment by longtimegamer** [comment]
It works but I don't like it... :) I have another idea to use better suited sidemissions. I will decline this PR.

**Comment by longtimegamer** [comment]
Ok I am resubmitting this PR with a different concept.  The code here will create a rescue sidemission (copied from x_m_51) and randomly place it inside the maintarget zone.  The pilots are moved into buildings near the crash site and ordered to lay prone and combatBehavior BLUE (no firing at all).  Then allowDamage is enabled and they are exposed to the war.  :)

I also updated the Zen_hallyg occupy script to avoid placing enemies in the same building as players/friendlies.  This means the pilots have a chance to hide quietly without an enemy spawning in the room with them.  However an enemy can discover them at any time!

If I coded this correctly, the default gameplay experience should not change.  If the new d_MissionType is selected then the embedded sidemission must be either win or fail so d_sm_nearby_cleared is set to true.

I've tested this on MP but it hasn't been running for very long.  If I discover problems I will certainly report and fix.

**Comment by Xeno69** [comment]
I'm not happy with that. Side missions should always be seperated from main targets.

It would be better to extend the main target missions instead and make them more diverse.

**Comment by longtimegamer** [comment]
Perhaps it can be written in a way that doesn't use the sidemission system?  I don't think it's required to include the sidemission markers, score, bonus vehicles, etc.  Maybe implement this PR in a different way, like you said extend the main target mission.

Unfortunately my server experiences are usually fairly small groups, less than 10 players.  There aren't enough players to play with a sidemission because the squads are too small and not fun and it separates the players too much.  As a result the sidemissions have been disabled for years on my server.  I'm sad to miss all the sidemissions and I would like to see them included where the players are focused.

The maintarget has secondary objectives that are limited to blowing up a static vehicle or building.  I would really like to see some of the more "exotic" sidemissions such as arrest, rescue or datatransfer.  Since you already created those missions there should be a way to connect them to maintarget?

**Comment by longtimegamer** [comment]
I think I see what you mean.  I can implement something similar to createsecondary in createmain which does not use the sidemission system.  That should not be too difficult.

**Pull request closed without merging**
